###
POST http://localhost:8080/recipe
Content-Type: application/json

{
  "nameRecipe": "Сырники из творога ",
  "time": 30,
  "unit": " мин.",
  "ingredients": [
    {
      "nameIngredient": "Творог ",
      "amount": 350,
      "unit": " гр."
    },
    {
      "nameIngredient": "Куриное яйцо",
      "amount": 2,
      "unit": " шт."
    },
    {
      "nameIngredient": "Пшеничная мука",
      "amount": 6,
      "unit": " ст.л."
    },
    {
      "nameIngredient": "Сахар",
      "amount": 2,
      "unit": " ст.л."
    }
  ],
  "preparingSteps": [
    "1.Смешайте весь творог с яйцами, сахаром и тщательно всё перемешайте. ",
    "2.Всыпьте в творог муку и тщательно перемешайте.",
    "3.Поставьте сковороду на средний огонь и налейте в нее подсолнечное масло.",
    "4.Слепите несколько небольших шариков из получившейся творожной массы и положите их на тарелку. Затем по очереди обкатывайте творожные шарики в муке и выкладывайте на сковороду. ",
    "5.Обжаривайте сырники 1–2 минуты до появления золотистой корочки. Затем переверните их на другую сторону и также обжарьте до золотистого состояния. ",
    "6.Повторяйте, пока творог не закончится."
  ]
}
###
GET http://localhost:8080/recipe/1
###
POST http://localhost:8080/recipe
Content-Type: application/json

{
  "nameRecipe": "Салат из красной фасоли с творожным сыром, красным луком и сезонным салатом ",
  "time": 7,
  "unit": " мин.",
  "ingredients": [
    {
      "nameIngredient": "Специи ",
      "amount": 0,
      "unit": "по вкусу"
    },
    {
      "nameIngredient": "Консервированная фасоль",
      "amount": 400,
      "unit": " гр."
    },
    {
      "nameIngredient": "Лимон",
      "amount": 1,
      "unit": " шт."
    },
    {
      "nameIngredient": "Чеснок",
      "amount": 2,
      "unit": " зуб."
    },
    {
      "nameIngredient": "Оливковое масло",
      "amount": 50,
      "unit": " мл."
    },
    {
      "nameIngredient": "Рукола",
      "amount": 100,
      "unit": " гр."
    },
    {
      "nameIngredient": "Творожный сыр",
      "amount": 200,
      "unit": " гр."
    },
    {
      "nameIngredient": "Красный лук ",
      "amount": 50,
      "unit": " гр."
    }
  ],
  "preparingSteps": [

    "1.Открыть две банки красной фасоли в собственном соку, слить сок и промыть фасоль холодной водой.",

    "2.Готовую фасоль смешать с мелко нарубленным красным луком, зеленью, давленым чесноком, оливковым маслом, лимонным соком и творожным сыром",

    "3.Посолить, поперчить, дать продуктам две минуты притереться друг к другу и подавать к столу."
  ]

}


